# Generated by Django 2.2 on 2019-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]

