# Generated by Django 2.2 on 2019-04-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_story_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='published',
        ),
    ]

