# Generated by Django 2.2.1 on 2019-05-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_story_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]

